apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-monitor-guardian
  namespace: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n-monitor-guardian
  template:
    metadata:
      labels:
        app: n8n-monitor-guardian
    spec:
      serviceAccountName: default
      containers:
        - name: n8n-monitor-guardian
          image: alpine:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              apk add --no-cache curl busybox-extras > /dev/null

              LOG_FILE="/tmp/guardian.log"
              NAMESPACE="ai"
              MONITOR_LABEL="app=n8n-monitor"
              PORT=9999

              echo "$(date -u '+%Y-%m-%d %H:%M:%S UTC'): Passive Guardian started." | tee -a $LOG_FILE

              # Background HTTP listener for heartbeats
              (
                while true; do
                  { 
                    echo -e "HTTP/1.1 200 OK\r\nContent-Length: 2\r\n\r\nOK" 
                  } | nc -lk -p $PORT -q 1
                done
              ) &

              LAST_HEARTBEAT=$(date +%s)

              while true; do
                NOW=$(date +%s)
                DIFF=$((NOW - LAST_HEARTBEAT))

                # Check heartbeat freshness
                if [ $DIFF -gt 60 ]; then
                  POD=$(kubectl -n $NAMESPACE get pod -l $MONITOR_LABEL -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)
                  if [ -n "$POD" ]; then
                    echo "$(date -u '+%Y-%m-%d %H:%M:%S UTC'): No heartbeat for ${DIFF}s, restarting pod $POD." | tee -a $LOG_FILE
                    kubectl -n $NAMESPACE delete pod "$POD" --grace-period=0 --force
                  fi
                  LAST_HEARTBEAT=$(date +%s)
                fi

                sleep 10
              done
          ports:
            - containerPort: 9999
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: n8n-monitor-guardian
  namespace: ai
spec:
  selector:
    app: n8n-monitor-guardian
  ports:
    - port: 9999
      targetPort: 9999
      protocol: TCP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monitor-guardian-role
  namespace: ai
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitor-guardian-binding
  namespace: ai
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ai
roleRef:
  kind: Role
  name: monitor-guardian-role
  apiGroup: rbac.authorization.k8s.io
