apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-guardian
  namespace: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n-guardian
  template:
    metadata:
      labels:
        app: n8n-guardian
    spec:
      serviceAccountName: default
      containers:
        - name: n8n-guardian
          image: bitnami/kubectl:1.30
          command: ["/bin/sh", "-c"]
          args:
            - |
              LOG_FILE="/tmp/n8n-guardian.log"
              MONITOR_LABEL="app=n8n-monitor"
              WEBHOOK_BOOT="http://192.168.0.59:32000/webhook/pi-boot"
              WEBHOOK_RECOVERED="http://192.168.0.59:32000/webhook/n8n-recovered"

              echo "$(date -u '+%Y-%m-%d %H:%M:%S UTC'): Guardian started." | tee -a $LOG_FILE

              while true; do
                MONITOR_POD=$(kubectl -n ai get pods -l $MONITOR_LABEL -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)

                if [ -z "$MONITOR_POD" ]; then
                  echo "$(date -u '+%Y-%m-%d %H:%M:%S UTC'): No monitor pod found, waiting 15s..." | tee -a $LOG_FILE
                  sleep 15
                  continue
                fi

                echo "$(date -u '+%Y-%m-%d %H:%M:%S UTC'): Found monitor pod: $MONITOR_POD" | tee -a $LOG_FILE

                if ! wget -q --spider "$WEBHOOK_BOOT"; then
                  echo "$(date -u '+%Y-%m-%d %H:%M:%S UTC'): Webhook check failed for $WEBHOOK_BOOT. Restarting monitor..." | tee -a $LOG_FILE
                  kubectl -n ai delete pod "$MONITOR_POD" --force --grace-period=0
                  sleep 20
                  continue
                fi

                if ! wget -q --spider "$WEBHOOK_RECOVERED"; then
                  echo "$(date -u '+%Y-%m-%d %H:%M:%S UTC'): Webhook check failed for $WEBHOOK_RECOVERED. Restarting monitor..." | tee -a $LOG_FILE
                  kubectl -n ai delete pod "$MONITOR_POD" --force --grace-period=0
                  sleep 20
                  continue
                fi

                sleep 30
              done
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi


