apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-guardian
  namespace: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n-guardian
  template:
    metadata:
      labels:
        app: n8n-guardian
    spec:
      containers:
        - name: n8n-guardian
          image: curlimages/curl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              LOG_FILE="/tmp/guardian.log"
              NAMESPACE="ai"
              MONITOR_LABEL="app=n8n-monitor"
              LAST_HEARTBEAT="/tmp/last_heartbeat"
              
              echo "$(date -u): Guardian started." | tee -a $LOG_FILE

              # Run HTTP server in background to receive heartbeats
              (while true; do
                 nc -l -p 8080 -q 1 | while read line; do
                   if echo "$line" | grep -q "POST /heartbeat"; then
                     date +%s > "$LAST_HEARTBEAT"
                     echo "$(date -u): Heartbeat received." | tee -a $LOG_FILE
                   fi
                 done
               done) &

              # Initialize timestamp
              date +%s > "$LAST_HEARTBEAT"

              # Monitor loop
              while true; do
                now=$(date +%s)
                last=$(cat "$LAST_HEARTBEAT")
                delta=$((now - last))

                if [ $delta -gt 120 ]; then
                  echo "$(date -u): No heartbeat for $delta seconds → restarting monitor..." | tee -a $LOG_FILE
                  POD=$(kubectl -n $NAMESPACE get pods -l $MONITOR_LABEL -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)
                  if [ -n "$POD" ]; then
                    kubectl -n $NAMESPACE delete pod "$POD" --grace-period=0 --force
                  else
                    echo "$(date -u): No monitor pod found to delete." | tee -a $LOG_FILE
                  fi
                  date +%s > "$LAST_HEARTBEAT"
                fi
                sleep 30
              done
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi

