apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-monitor-guardian
  namespace: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n-monitor-guardian
  template:
    metadata:
      labels:
        app: n8n-monitor-guardian
    spec:
      serviceAccountName: default
      containers:
        - name: n8n-monitor-guardian
          image: busybox:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              LOG_FILE="/tmp/n8n-guardian.log"
              MONITOR_LABEL="app=n8n-monitor"
              NAMESPACE="ai"
              TIMEOUT=60

              echo "$(date -u '+%Y-%m-%d %H:%M:%S UTC'): Passive Guardian started." | tee -a $LOG_FILE

              # Find monitor pod
              while true; do
                POD_NAME=$(kubectl -n $NAMESPACE get pod -l $MONITOR_LABEL -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)
                if [ -n "$POD_NAME" ]; then
                  echo "$(date -u '+%Y-%m-%d %H:%M:%S UTC'): Found monitor pod $POD_NAME" | tee -a $LOG_FILE
                  break
                fi
                echo "$(date -u '+%Y-%m-%d %H:%M:%S UTC'): No monitor pod found, waiting 10s..." | tee -a $LOG_FILE
                sleep 10
              done

              LAST_HEARTBEAT=$(date +%s)
              echo "$(date -u '+%Y-%m-%d %H:%M:%S UTC'): Listening for heartbeats on port 8080..." | tee -a $LOG_FILE

              # Background listener for HTTP heartbeats
              while true; do
                # Start listener in background (BusyBox nc lacks -q)
                ( echo -e "HTTP/1.1 200 OK\r\nContent-Length: 2\r\n\r\nOK" | nc -l -p 8080 -v > /dev/null 2>&1 ) &
                LISTENER_PID=$!

                # Wait for heartbeat or timeout
                for i in $(seq 1 $TIMEOUT); do
                  if [ -f /tmp/heartbeat.received ]; then
                    rm -f /tmp/heartbeat.received
                    LAST_HEARTBEAT=$(date +%s)
                    echo "$(date -u '+%Y-%m-%d %H:%M:%S UTC'): Heartbeat received." | tee -a $LOG_FILE
                    break
                  fi
                  sleep 1
                done

                # Check time since last heartbeat
                NOW=$(date +%s)
                DIFF=$((NOW - LAST_HEARTBEAT))
                if [ $DIFF -ge $TIMEOUT ]; then
                  echo "$(date -u '+%Y-%m-%d %H:%M:%S UTC'): No heartbeat in $DIFFs → restarting monitor pod..." | tee -a $LOG_FILE
                  kubectl -n $NAMESPACE delete pod "$POD_NAME" --grace-period=0 --force
                  LAST_HEARTBEAT=$(date +%s)
                fi

                kill $LISTENER_PID 2>/dev/null
              done
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monitor-guardian-role
  namespace: ai
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitor-guardian-binding
  namespace: ai
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ai
roleRef:
  kind: Role
  name: monitor-guardian-role
  apiGroup: rbac.authorization.k8s.io
