apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-monitor-guardian
  namespace: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n-monitor-guardian
  template:
    metadata:
      labels:
        app: n8n-monitor-guardian
    spec:
      serviceAccountName: default
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: n8n-monitor-guardian
          image: alpine/k8s:1.28.3
          command: ["/bin/sh", "-c"]
          args:
            - |
              LOG_FILE="/tmp/n8n-guardian.log"
              MONITOR_DEPLOY="n8n-monitor"
              NAMESPACE="ai"
              HEARTBEAT_PORT=9999
              LAST_HEARTBEAT=$(date +%s)

              echo "$(date -u '+%Y-%m-%d %H:%M:%S UTC'): Passive Guardian started (host network mode)." | tee -a $LOG_FILE

              # Background listener for heartbeats
              (
                while true; do
                  echo "Listening for heartbeat on port $HEARTBEAT_PORT..." | tee -a $LOG_FILE
                  nc -lk -p $HEARTBEAT_PORT >/dev/null 2>&1 && LAST_HEARTBEAT=$(date +%s)
                done
              ) &

              # Guardian loop
              while true; do
                NOW=$(date +%s)
                DIFF=$((NOW - LAST_HEARTBEAT))

                POD_NAME=$(kubectl -n $NAMESPACE get pod -l app=$MONITOR_DEPLOY -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)

                if [ -z "$POD_NAME" ]; then
                  echo "$(date -u '+%Y-%m-%d %H:%M:%S UTC'): ⚠️ No monitor pod found, waiting 10s..." | tee -a $LOG_FILE
                  sleep 10
                  continue
                fi

                if [ "$DIFF" -gt 60 ]; then
                  echo "$(date -u '+%Y-%m-%d %H:%M:%S UTC'): ⏱️ No heartbeat for ${DIFF}s, restarting monitor pod ($POD_NAME)." | tee -a $LOG_FILE
                  kubectl -n $NAMESPACE delete pod "$POD_NAME" --grace-period=0 --force
                  LAST_HEARTBEAT=$(date +%s)
                fi

                sleep 5
              done
          ports:
            - containerPort: 9999
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monitor-guardian-role
  namespace: ai
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitor-guardian-binding
  namespace: ai
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ai
roleRef:
  kind: Role
  name: monitor-guardian-role
  apiGroup: rbac.authorization.k8s.io

