apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: n8n-guardian-role
  namespace: ai
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]
